server:
  port: 8080

spring:
  application:
    name: order-service
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/security?autoReconnect=true&characterEncoding=utf8
    username: root
    password: lizhimysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    #generate-ddl: true
    properties:
      hibernate.format_sql: true
    open-in-view: false

security:
  oauth2:
    client:
      client-id: orderService
      client-secret: 123456
    resource:
      jwt:
        key-uri: http://auth-server:8090/oauth/token_key