spring:
  application:
    name: item-service

server:
  port: 8082

security:
  oauth2:
    client:
      client-id: itemService
      # client-secret: 123456
    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAka+mJhdCijfGnPaZvBdgQwHboZdxzjShpFyVK3x7Cu8r6rr45F0YpYElfgUci2oDRDdZPABZHk2jXYh9k/bExLshQMAc3DtdE4bt46nlmKGQsA9QZXEQq11rrYYY4yX5/oH8rWjW/GCaK+NeY/mILMRuP0XSxFlG1zPqhnn0r3gFHPJ9iFRFBtfZ98kRrx2I+XTy85ItxKhZgCgG8bdHoaRMDItYK2lz7v4sCeQY24pj+zc1ytprFB29fixR2Ss90Aw1Xa7Dl540EisIdTF+7n5bjjD1PUxwsKBveRCGxYXI7Hf7Fa2+pEMlXlqpYcuivYmMGtDh9srdfWvpUvv4PwIDAQAB
          -----END PUBLIC KEY-----
